version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: lmsDB
    environment:
      POSTGRES_DB: lmsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  main-service:
    build:
      context: ./main-service
    container_name: main_service_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lmsDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.yaml

volumes:
  pgdata:
