version: "3.8"

services:
  # PostgreSQL для твоего приложения
  postgres:
    image: postgres:15
    container_name: lmsDB
    environment:
      POSTGRES_DB: lmsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # PostgreSQL для Keycloak
  keycloak-db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "55433:5432"
    volumes:
      - kc_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: "true"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    ports:
      - "8081:8080"

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Твой основной сервис
  main-service:
    build:
      context: ./main-service
    container_name: main_service_container
    depends_on:
      - postgres
      - keycloak
      - minio
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lmsDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.yaml

      MINIO_URL: http://minio:9000
      MINIO_USER: minio
      MINIO_PASSWORD: minio123
      MINIO_BUCKET: lms-attachments

volumes:
  pgdata:
  kc_pgdata:
  minio_data:
